# Generated by Django 4.2.6 on 2025-03-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworksDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_name', models.CharField(max_length=32)),
                ('int_name', models.CharField(max_length=32)),
                ('int_ipaddr', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_code', models.CharField(max_length=5)),
                ('obj_name', models.CharField(max_length=128)),
                ('obj_addr', models.CharField(max_length=256)),
            ],
        ),
    ]
